### PR TITLE
feat: bump docker component versions

### PR DESCRIPTION
**Pull request by jingkaihe**
Hi :wave: 

Thanks for providing the awesome concourse-dind image.

I made a few tweaks on your concourse-dind, namely:

* use `ubuntu:focal` as the base image
* bump the docker & compose version to newer versions
* some bash script fixes

### CODE REVIEW

**Comment by ramizpolic** [comment]
Awesome work @jingkaihe, thanks for taking the time to update the deps! I will add the GA today/tomorrow to cover the test suite. Will be able to merge it then 🚀

**Comment by sebbonnet** [comment]
Hi @ramizpolic, have you been able to review this work? Let us know if any changes is required.

**Comment by ramizpolic** [comment]
Sorry for the delay @jingkaihe, this one is on me. Added GH actions to publish the image. Please rebase and we can merge this one

**Comment by ULis3h** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
u2, @z0rats, @xd4rker, @bmiller59, @rjakobsson, @sami-abdul, @howie1013, @Murphy-hub, @miguelrfernandes, @sabrinekhoualdi, @i838847058, @leonardovoss, @logix, @sherlok235, @OganBelema, @Zowie, @Mantak, @jimmyoz, @hborska, @gt2140

**Comment by jingkaihe** [comment]
@ramizpolic thanks, just rebased!

**Comment by ramizpolic** [comment]
released in v2.0.0, thanks a lot for the contribution @jingkaihe!

**Pull request merged**
